### ISSUE TITLE
I have lots of document for custom translator and want to upload programmatically from specific location

### ISSUE THREAD

**Issue by anomepani** [MicrosoftTranslator/Text-Translation-API-V3-C-Sharp#7]
I have lots of document for a custom translator and want to upload programmatically from a specific location. Is there a way to do so?
Using manual approach its very time consuming, Is there any API or SDK available for C#?

If so Please provide sample demo So I can utilize.

**Comment by chriswendt1** [comment]
https://github.com/MicrosoftTranslator/CustomTranslatorApiSamples
